### ISSUE TITLE
How could I identify the root-cause invocation by a single label in each trace object?

### ISSUE THREAD

**Issue by facefff** [NetManAIOps/TraceRCA#1]
For example:
![image](https://user-images.githubusercontent.com/51893660/133741257-01b72749-1e16-49d9-917f-e902e41cd63d.png)

This is an trace object in /A/API/route_delay_0414.pkl.
There are tens of invocations in this trace, how could I know which invocation is the root-cause.
Otherwise, I could not evaluate my RCA model without root-cause labels.
Thanks for any reply!

**Comment by lizeyan** [comment]
The root-cause services are labeled in the filenames.
For example, `route_delay_0414` means the root cause is `route` and the fault type is `delay`. (`0414` is just a timestamp. Ignore it).
The root-cause invocations are unknown.

**Comment by facefff** [comment]
> The root-cause services are labeled in the filenames.
> For example, `route_delay_0414` means the root cause is `route` and the fault type is `delay`. (`0414` is just a timestamp. Ignore it).
> The root-cause invocations are unknown.

So, data above shows that it is an anomalous trace(label = 1) and the service named 'ui-dashboard'(root service in the trace) is the root cause service?

**Comment by lizeyan** [comment]
> > The root-cause services are labeled in the filenames.
> > For example, `route_delay_0414` means the root cause is `route` and the fault type is `delay`. (`0414` is just a timestamp. Ignore it).
> > The root-cause invocations are unknown.
> 
> So, data above shows that it is an anomalous trace(label = 1) and the service named 'ui-dashboard'(root service in the trace) is the root cause service?

No.
The root-cause service is the service that we injected faults on and it is labeled in the filename only.
So the root cause for all traces in `/A/API/route_delay_0414.pkl` is `route`.
Though for a single trace, it can be anomalous due to other reasons. But we are only concerned about the root cause of the system at that time, which is `route` definitely, rather than those of single traces.

**Comment by lizeyan** [comment]
I mean, there is not exactly a root-cause service for a single trace in our scenario. We only care about the root-cause service of the whole system

**Comment by facefff** [comment]
OK, I've completely understood.
Thanks again.
