### ISSUE TITLE
关于run_localization_collect.py的输出结果

### ISSUE THREAD

**Issue by chiyun1111** [NetManAIOps/TraceRCA#11]
作者你好，想请问下关于这个py文件的一些输出结果与论文不对应的问题：

1、这是microservice的输出结果，与论文中的结果差不多，top3有0.96，论文上是0.97。
<img width="277" alt="d328e97b20bf6c62784668eb4ccbadc" src="https://user-images.githubusercontent.com/68764410/173034007-a0bb406c-fca7-4232-a37f-4ff4ca36ca6f.png">
2、这是container的输出结果，但是top3只有0.5，论文上是0.8。
<img width="203" alt="905a80747bf320d67e59e016be54a22" src="https://user-images.githubusercontent.com/68764410/173034337-19688979-9e3f-49b2-8c5d-d2a442152770.png">
3、这是API的输出结果，top3也只有0.57，论文上是0.83。
<img width="236" alt="875eb6ffc9a2040e633bc98d6528f7c" src="https://user-images.githubusercontent.com/68764410/173034801-aecdf84b-36ef-4209-8c76-25156d6312be.png">

也就是说API和container的top3效果都不太好，不知道作者您这边有没有什么解决方法，是输入的uninjection中源数据的问题（四个pkl文件我都尝试了，效果差不多），还是后面参数设置的问题？抑或是其他的py文件中作者您选用了其他的函数？因为我就只使用了作者您在代码上默认的函数。

麻烦您抽空解答下，万分感谢！

**Comment by lizeyan** [comment]
可以试一下用全部的正常数据。实验脚本的用法和参数设置参考makefile

**Comment by chiyun1111** [comment]
好的，非常感谢！
