### ISSUE TITLE
run_anomaly_detection_trace.py文件缺失

### ISSUE THREAD

**Issue by renjiedai** [NetManAIOps/TraceRCA#18]
作者您好，我在Makefile文件中看到使用run_anomaly_detection_trace.py脚本生成TRACE_TEST_FILE_RESULTS，但是在仓库文件中并没有找到run_anomaly_detection_trace.py文件，请问可以提供一下该脚本文件吗？感谢！
![image](https://user-images.githubusercontent.com/69706664/229279863-9bc9f660-ebb8-4ab1-8a0f-c41774abf8e3.png)

**Comment by lizeyan** [comment]
已经加上来了
