### ISSUE TITLE
关于trace中数据格式

### ISSUE THREAD

**Issue by BasiurII** [NetManAIOps/TraceRCA#19]
![图片1](https://github.com/NetManAIOps/TraceRCA/assets/49359286/a7f83b18-0db9-43d0-89d4-8315d74db007)
作者您好，我看您在论文中说cpu_use和mem_use_percent是每个微服务的指标，但这个trace里两次调用涉及到了三个微服务，cpu_use字段只有两个值，微服务和cpu_use是怎么对应起来的？

**Comment by lizeyan** [comment]
ingressgateway不是一个微服务，只是网关而已，没有算它的机器性能指标

**Comment by BasiurII** [comment]
> ingressgateway不是一个微服务，只是网关而已，没有算它的机器性能指标

![图片1](https://github.com/NetManAIOps/TraceRCA/assets/49359286/131bbd1a-3612-4e58-9fc4-11a6170fd1f0)
谢谢作者，那就是按微服务出现的顺序跟cpu_use指标对应吗，就像这张图里面。
![YTC 8O UY$ VXSO%H92CVE](https://github.com/NetManAIOps/TraceRCA/assets/49359286/ae13cddc-3342-4445-8751-d00cb52318d9)
但是这个trace有两个微服务，指标只有一个。

**Comment by lizeyan** [comment]
每个指标和每个tuple中的后一个microservice对应。即21.685是ts-station-service的CPU使用率。这是因为这个span是ts-order-service发给ts-station-service的请求，大多数实际的计算是在ts-station-service上进行的。所以我们都只考虑服务方（station）的机器指标，不考虑请求方（order）

**Comment by BasiurII** [comment]
> 每个指标和每个tuple中的后一个microservice对应。即21.685是ts-station-service的CPU使用率。这是因为这个span是ts-order-service发给ts-station-service的请求，大多数实际的计算是在ts-station-service上进行的。所以我们都只考虑服务方（station）的机器指标，不考虑请求方（order）

好的，明白了，谢谢作者。
