### ISSUE TITLE
端点服务问题

### ISSUE THREAD

**Issue by theoryXie** [NetManAIOps/TraceRCA#3]
作者您好，我阅读了您的论文后，有一个小疑问，我发现一个Trace的两端的服务总是可以获得较高的评分：
比如trainticket的travel服务，因为它总是位于trace的第一个服务，所以在计算服务内得分的时候总是很高，请问这种问题您是这么解决的

**Comment by lizeyan** [comment]
如论文里的描述，in-set score的设计目标本来其实就是偏好异常链路上两端的服务的。这是因为我们认为故障一般不会同时向上游和下游传播，而是沿一个方向传播。
对于非根因的端点服务，如果它是正常的（invocation都是正常的）那自然不会被定位；如果有异常invocation的，我们是认为它的confidence会比较低，因为这样的端点可能是公共服务，会有很多别的没受到根因影响的trace也经过了它。
对于train ticket的注入的故障来说，以上的结论基本都是成立的，按我们的经验定位不准的情况大多数是异常检测不准确。

**Comment by theoryXie** [comment]
我觉得您说的很对，我也怀疑是异常检测的问题，我复现了您的论文后，采用了您的A数据集，在异常检测的时候采用了您论文中的算法：

- 与前几天的数据作mean和std的计算
- 与前几分钟的数据作mean和std的计算
数据集中未注入异常的是这几个时间段
![image](https://user-images.githubusercontent.com/43115955/143682694-be02e987-8db5-4008-8ecb-949f55c2f217.png)
用于测试的数据其实有很多不是对应时间的（比如存在4月25日的数据，目前我是就近取的正常数据作为对比），并且如果用前几分钟的数据，会不会存在前几分钟本来就是异常的情况，用来参考的话，是不是会存在偏差？（这是我复现时的思考，以下是我在A数据集API文件夹复现的结果：）
![image](https://user-images.githubusercontent.com/43115955/143683225-2b25a456-9031-4809-9898-8bd5b70acae2.png)
您觉得这个结果是异常检测的问题吗（目前采用的t-mean/std的方法）

**Comment by lizeyan** [comment]
"如果用前几分钟的数据，会不会存在前几分钟本来就是异常的情况", 一般是不会的, 这个数据注入故障的时候故障注入的间隔比较长, 至少应该10分钟之内都没有别的故障
另外你可以试试直接用所有的未注入时段的数据去算mean和std. 因为这个数据上注入的故障都比较明显, 基本应该都是已经明显超过数据的正常范围的那种value outliers了. 只用前几分钟可能异常检测的波动比较大.
