### ISSUE TITLE
关于代码的运行问题

### ISSUE THREAD

**Issue by fallingleaflun** [NetManAIOps/TraceRCA#5]
1. 请问您提供的源码中cache_file是什么，我在你提供的https://cloud.tsinghua.edu.cn/d/8371855eddd64a8db23b/files/?p=%2FA.zip 这个数据集中没有找到？
2. 我尝试修改你的代码并在上述这个A数据集中运行，一些操作细节如下
    - history数据我选用的是uninjection的3.pkl
    - 初始使用feature如下
      FEATURE_NAMES = ['latency', 'cpu_use', 'mem_use_percent', 'mem_use_amount', 'file_write_rate', 'file_read_rate', 'net_send_rate', 'net_receive_rate']，通过run_selecting_features.py确实筛选出了各个(source, target)的有效feature
    - 但是最后得到的效果却很差
       以admin-order_abort_1011.pkl为例，异常调用检测的准确率只有0.67
    ![image](https://user-images.githubusercontent.com/32243069/167859040-b1d8c5bd-b7b0-47e3-9df6-00100dc13e0c.png)
       由于检测可能就有问题，所以根因定位也很差
    ![image](https://user-images.githubusercontent.com/32243069/167855823-c2865946-cf21-4464-bfe2-2a6595b2f168.png)

还有就是以下这段代码是什么意思？我直接把:=改成=了
![image](https://user-images.githubusercontent.com/32243069/167856189-b9794736-1b88-445d-9506-ff84d48efeca.png)

我想知道这个代码是如何运行的？

**Comment by lizeyan** [comment]
- cache_file是其他脚本的输出，保存了训练好的模型。我好像忘了上传了，我后续补一下
- `:=`是Python3.8的新语法

**Comment by fallingleaflun** [comment]
我看代码感觉这个cache_file就是记录了正常调用对的均值和方差不是吗，所以我在run_selecting_features.py中把history中的各调用对的均值和方差都保存在cache_file里面进行下一步了，难道不是这样？我很好奇！

**Comment by lizeyan** [comment]
> 差都保存在cache_file里面进行下一步了，难道不是这样？我很好奇！

是这样。我把之前漏了的代码也上传了

**Comment by fallingleaflun** [comment]
我看了一下你的makefile，发现文件夹的结构和你提供的数据集的文件夹不一致，方便说明一下文件结构吗？就比如说下面这个data文件夹的四个文件夹如果要使用A数据集的数据，应该怎样准备数据
![image](https://user-images.githubusercontent.com/32243069/168970406-06a044db-44ca-41a2-a58c-e7940470b472.png)

**Comment by fallingleaflun** [comment]
> 我看了一下你的makefile，发现文件夹的结构和你提供的数据集的文件夹不一致，方便说明一下文件结构吗？就比如说下面这个data文件夹的四个文件夹如果要使用A数据集的数据，应该怎样准备数据 ![image](https://user-images.githubusercontent.com/32243069/168970406-06a044db-44ca-41a2-a58c-e7940470b472.png)

@lizeyan

**Comment by lizeyan** [comment]
makefile里的ORIGIN_DATA_DIR需要按照具体情况改成需要测试的数据集的路径
