### ISSUE TITLE
作者你好，关于代码各个模块有一些输入文件方面的疑惑，希望能够解答

### ISSUE THREAD

**Issue by wentao-ucas** [NetManAIOps/TraceRCA#7]
之前做了一些数据集，但是top-k准确率很低，有一些疑问想问一下作者。
**1. 例如我想测试A数据集中API的根因**
python prepare_train_file_tmp.py将数据集进行划分
train_dir = Path(r'D:\GitHub\rca1\TraceRCA\train\API')
test_dir = Path(r'D:\GitHub\rca1\TraceRCA\test\API')
因为一开始未注意到run_invo_encoding.py，所以是通过写了个函数flatten来将pkl转换为dataframe（simple_name已经在问题中看到回答了）
def flatten(pkl):
    df = pd.DataFrame(pkl)
    cols = list(df.columns)
    cols.remove('trace_id')
    cols.remove('label')
    df = df.explode(cols)
    df = df.reset_index(drop=True)
    df['source'] = df['s_t'].apply(lambda x: x[0])
    df['target'] = df['s_t'].apply(lambda x: x[1])
    df = df.drop('s_t', axis=1)
    return df
数据集划分后进行selecting feature

 **2. Run Selecting Feature**
 例如我想定位\API\basic_delay_0414.pkl的根因，我不太明白输入是什么，我之前将test文件夹作为input，train作为
 history，但最后根因定位结果很差，所以像问一下，这个input和history指的是什么文件
@click.command('invocation feature selection')
@click.option('-i', '--input', 'input_file', default="*.pkl", type=str)
@click.option('-o', '--output', 'output_file', default='.', type=str)
@click.option('-h', '--history', default='historical_data.pkl', type=str)
@click.option("-f", "--fisher", "fisher_threshold", default=1, type=float)

test1
input_file = r'D:\GitHub\rca1\TraceRCA\test\API\basic_delay_0414.pkl'
output_file = r'D:\GitHub\rca1\TraceRCA\output\feature\API\basic_delay_0414'
history = r'D:\GitHub\rca1\TraceRCA\train\API\basic_delay_0414.pkl'
fisher_threshold=1

我又在GitHub上看到一位朋友给作者提的问题，将uninjection中的pkl作为history，但是我试了一下，结果更差
test2
input_file = r'D:\GitHub\rca1\TraceRCA\test\API\basic_delay_0414.pkl'
output_file = r'D:\GitHub\rca1\TraceRCA\output\feature\API\basic_delay_0414'
history = r'D:\GitHub\rca1\TraceRCA\dataset\test\3.pkl'
fisher_threshold=1

所以Run Selecting Feature这部分就是想弄清楚input和history指的是什么文件

 **3. Run_anomaly_detection_prepare_model**
这部分也是想弄清楚invo_history和trace_history指的是什么文件
同时对于cache文件来说，是每一个pkl文件在训练的时候，都需要生成一个cache，还是说，我生成一个cache可以适用于所有的文件。

@click.command('train-anoamly-detection-model')
@click.option('-i', '--invo-history', default='historical_data.pkl', type=str)
@click.option('-t', '--trace-history', default='historical_data.pkl', type=str)
@click.option('-o', '--output-file', type=str)

invo_history = r'D:\GitHub\rca1\TraceRCA\test\API\basic_delay_0414.pkl'
output_file = r'D:\GitHub\rca1\TraceRCA\output\cache\basic_delay_0414'
trace_history = r'D:\GitHub\rca1\TraceRCA\train\API\basic_delay_0414.pkl'

因为一开始未用到run_trace_encoding.py, 所以也是将extract_data做了一些调整，其中data后续做了reshape(len(data), -1)这个操作。（没有的指标会注释）

def extract_data(path):
    x = np.load(path, allow_pickle=True)
    x = pd.DataFrame(x).astype({
        'trace_id': 'str',
        'timestamp': 'float',
        'latency': 'float',
        'http_status': 'float',
        'cpu_use': 'float',
        'mem_use_percent': 'float',
        'mem_use_amount': 'float',
        'file_write_rate': 'float',
         'file_read_rate': 'float',
         'net_send_rate': 'float',
         'net_receive_rate': 'float',
         'endtime': 'float',
         'source': 'str',
         'target': 'str',
         'label': 'int'
    })
    data = x[[
              'latency', 
              'http_status', 
               'cpu_use', 
               'mem_use_percent', 
               'mem_use_amount', 
               'file_write_rate',
               'file_read_rate',
               'net_send_rate',
               'net_receive_rate'
             ]]
    x['labels'] = x['label']
    #x['masks'] = x['http_status']
    x['trace_ids'] = x['trace_id']
    return data, x['labels'], x['trace_ids']

**4. run_anomaly_detection_invo**
我的理解是input_file是test\API\basic_delay_0414.pkl
 history是train\API\basic_delay_0414.pkl
 cache和useful_feature就是刚刚生成的文件
但好像也是有点问题
这部分也是想弄清楚input_file和history指的是什么文件
代码中有一行history = None ，应该是不需要history

@click.command('invocation anomaly detection')
@click.option('-i', '--input', 'input_file', default="*.pkl", type=str)
@click.option('-o', '--output', 'output_file', default='.', type=str)
@click.option('-h', '--history', default='historical_data.pkl', type=str)
@click.option('-u', '--useful-feature', "useful_feature", default='.', type=str)
@click.option('-c', '--cache', 'cache_file', default='.', type=str)
@click.option('-t', '--threshold', 'main_threshold', default=1, type=float)

input_file = r'D:\GitHub\rca1\TraceRCA\test\API\basic_delay_0414.pkl'
history = r'D:\GitHub\rca1\TraceRCA\train\API\basic_delay_0414.pkl'
output_file = r'D:\GitHub\rca1\TraceRCA\output\anomaly\API\basic_delay_0414'
useful_feature = r'D:\GitHub\rca1\TraceRCA\output\feature\API\basic_delay_0414' 
cache_file = r'D:\GitHub\rca1\TraceRCA\output\cache\basic_delay_0414'
main_threshold = 1

**5.run_anomaly_detection_collect_result.py**
这个不清楚的是invo_input_files和trace_input_files是什么
我的理解是invo_input_files是刚刚run_anomaly_detection_invo的输出
但是trace_input_files是指的什么了？

@click.command('collect result main')
@click.option("-i", "--invo-input", "invo_input_files", multiple=True)
@click.option("-t", "--trace-input", "trace_input_files", multiple=True)
@click.option("-o", "--output", "output_file")

**6 run_localization_association_rule_mining**
这个输入没有什么太大疑问，我的理解是将run_anomaly_detection_invo的输出作为输入
@click.command('association rule mining')
@click.option("-i", "--input", "input_file")
@click.option("-o", "--output", "output_file")
@click.option("--min-support-rate", default=0.1)
@click.option("--enable-PRFL", is_flag=True)
@click.option("--k", default=100)
@click.option("--quiet", "-q", is_flag=True)

在最后TraceRCA排序上，我看到了倒序排列，如果没有理解错，我想看top-3准确率就是看最后三个中有没有basic?
文件为\API\basic_delay_0414.pkl
        ret = sorted(
            itemset_handler.items,
            key=lambda _item: (item_ret[_item]["score"], -len(item_ret[_item]["pattern"])),
            reverse=True,
        )

**7. run_localization_collect.py**
同时看到input_file是一个list，如果我想评估A数据集API数据，那么是将API文件夹中的所有文件根因定位的文件名作为
一个列表吗？(run_anomaly_detection_collect_result的输出)
例如input_file_list = ['\basic_delay_0414', '\basic_delay_0420',...,'\user_delay_0421']

@click.command("")
@click.option("-i", "--input_file", "input_file_list", multiple=True)
@click.option("-o", "--output", "output_file")
@click.option("-r", "--root-cause", default="")

**Comment by lizeyan** [comment]
具体流程、每一步的输入输出的话可以参考我放的makefile。

**Comment by wentao-ucas** [comment]
你好，我已经收到你的邮件，谢谢。

**Comment by chiyun1111** [comment]
你好，请问你的问题解决了吗，可以把作者的回复邮件也发我一份嘛，感谢

**Comment by wentao-ucas** [comment]
咋发啊😳



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月6日(周一) 下午4:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [NetManAIOps/TraceRCA] 作者你好，关于代码各个模块有一些输入文件方面的疑惑，希望能够解答 (Issue #7)




 
你好，请问你的问题解决了吗，可以把作者的回复邮件也发我一份嘛，感谢

**Comment by chiyun1111** [comment]
我的邮箱是chiyun1111@163.com
麻烦啦~感谢

**Comment by tybalex** [comment]
你好， 请问可以把作者的回复邮件也发我一份嘛。。感谢。。我的邮箱是tybalex@gmail.com

**Comment by wentao-ucas** [comment]
你好，我已经收到你的邮件，谢谢。

**Comment by wentao-ucas** [comment]
> 你好， 请问可以把作者的回复邮件也发我一份嘛。。感谢。。我的邮箱是[tybalex@gmail.com](mailto:tybalex@gmail.com)

作者没给我发邮件，我那个是邮箱自动回复，内容就是“具体流程、每一步的输入输出的话可以参考我放的makefile。”

**Comment by wentao-ucas** [comment]
你好，我已经收到你的邮件，谢谢。
