### ISSUE TITLE
prepare_train_file_tmp.py 中train和test的问题

### ISSUE THREAD

**Issue by chiyun1111** [NetManAIOps/TraceRCA#9]
作者你好，我这里有几个问题想请教下
1、请问prepare_train_file_tmp.py这个文件下的train和test数据指的是什么数据呢，我看到后面的异常检测和根因定位的代码中也没有用到有关train和test的数据呀，请问它们的作用是什么呢？
2、我理解的代码中history指的是uninjection中的数据，但是uninjection有4个pkl文件，并且文件所包含的指标数量也不同，这里该怎么选择呢？还有就是文章中说history用到了两个阶段的数据去计算均值和方差，但实际代码中我好像只看到计算了一个阶段的数据，那另一个阶段的数据该怎么选择呢，您给的数据集里面有包含吗？

**Comment by lizeyan** [comment]
`prepare_train_file_tmp.py`是用来将注入故障时段的trace分成训练集和测试集的。后面有监督模型（baseline）的异常检测和根因定位需要用到训练集。
uninjection中只是未注入故障时段的一些数据，不包括'last slot'的数据。“用到了两个阶段的数据去计算均值和方差”这个是通过手动处理出一个新的pkl文件去做的

**Comment by chiyun1111** [comment]
好的，非常感谢你的解答！
另外还想问一下，makefile里面的有一些py文件在你提供的code里面我没找到，比如run_dataset_summary.py、run_trace_encoding.py、run_invo_encoding.py等等，请问这些代码在哪里呢？以及cache_file文件我好像也没有看到呢。

**Comment by lizeyan** [comment]
cache_file是需要自己跑训练模型的脚本才能得到的。其他缺了的我再补一下

**Comment by chiyun1111** [comment]
好的，十分感谢！

**Comment by fallingleaflun** [comment]
请问你后面把代码跑起来了吗？make ad跑到后面发现没有run_anomaly_detection_trace.py
